# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Incarcloud settings
incarcloud:
  swagger2:
    api:
      title: 问候项目在线API文档
      description: 本文档包含该项目全部业务接口，注意保密。(by incar)
      service-url: http://localhost:8080/doc.html
      version: 0.0.2-SNAPSHOT
